const TEMP_OVERWRITE_STATE_NONE = 0;
const TEMP_OVERWRITE_STATE_LOW_TEMP = 1;
const TEMP_OVERWRITE_STATE_HIGH_TEMP = 2;

const debugSettings = {
    tempOverwriteState: TEMP_OVERWRITE_STATE_NONE
}

export {debugSettings,TEMP_OVERWRITE_STATE_NONE,TEMP_OVERWRITE_STATE_LOW_TEMP,TEMP_OVERWRITE_STATE_HIGH_TEMP};